package edu.epn.wachiteam.moviles.coco_tourism

import android.app.Activity
import android.content.pm.PackageManager
import androidx.core.content.ContextCompat
import android.Manifest
import android.content.Context
import android.graphics.Bitmap
import android.graphics.BitmapFactory
import android.location.Location
import android.os.Build
import android.os.Parcel
import android.os.Parcelable
import android.util.Log
import androidx.annotation.RequiresApi
import androidx.core.app.ActivityCompat
import com.android.volley.Request
import com.android.volley.RequestQueue
import com.android.volley.toolbox.BasicNetwork
import com.android.volley.toolbox.DiskBasedCache
import com.android.volley.toolbox.HurlStack
import com.android.volley.toolbox.JsonObjectRequest
import com.google.android.gms.location.LocationServices
import com.google.android.gms.maps.model.LatLng
import com.google.android.libraries.places.api.Places
import com.google.android.libraries.places.api.model.Place
import com.google.android.libraries.places.api.net.FindCurrentPlaceRequest
import com.google.android.libraries.places.api.net.PlacesClient
import edu.epn.wachiteam.moviles.coco_tourism.services.Globals.Maps.API_KEY
import edu.epn.wachiteam.moviles.coco_tourism.services.Location.Companion.context
import edu.epn.wachiteam.moviles.coco_tourism.services.Location.Companion.getLocation
import edu.epn.wachiteam.moviles.coco_tourism.services.MapPlaces
import org.chromium.base.Promise
import java.io.BufferedInputStream
import java.io.ByteArrayOutputStream
import java.io.FileNotFoundException
import java.io.FileOutputStream
import java.io.InputStream
import java.io.ObjectInputStream
import java.io.ObjectOutputStream
import java.net.HttpURLConnection
import java.net.URL
import java.util.stream.Collectors
import java.util.stream.Stream
import javax.net.ssl.HttpsURLConnection
import kotlin.concurrent.thread

class TestInit(val activity: Activity) {
}